CREATE TABLE IF NOT EXISTS post_contributors(
ct_id INT NOT NULL AUTO_INCREMENT,
pt_id INT NOT NULL,
content VARCHAR(200) NOT NULL,
PRIMARY KEY(ct_id),
FOREIGN KEY(pt_id) REFERENCES post(pt_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;