CREATE TABLE IF NOT EXISTS post(
pt_id INT NOT NULL AUTO_INCREMENT,
_id VARCHAR(30) NOT NULL,
namespace INT NOT NULL,
title VARCHAR(500) NOT NULL,
_text MEDIUMTEXT NOT NULL,
rand_num INT NOT NULL,
PRIMARY KEY(pt_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;